"""add authentication credentials

Revision ID: 10065d6c0ba7
Revises: 898c84cd6b8e
Create Date: 2026-08-16 12:54:50.694341
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "10065d6c0ba7"
down_revision: str | None = "898c84cd6b8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > created_at",
            name=op.f("ck_api_tokens_expiry_after_creation"),
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
            name=op.f("fk_api_tokens_principal_id_principals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_api_tokens_token_hash")),
    )
    op.create_index(op.f("ix_api_tokens_expires_at"), "api_tokens", ["expires_at"], unique=False)
    op.create_index(
        "ix_api_tokens_principal_active",
        "api_tokens",
        ["principal_id", "revoked_at", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_tokens_principal_id"), "api_tokens", ["principal_id"], unique=False
    )
    op.create_index(op.f("ix_api_tokens_revoked_at"), "api_tokens", ["revoked_at"], unique=False)
    op.create_table(
        "password_credentials",
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
            name=op.f("fk_password_credentials_principal_id_principals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("principal_id", name=op.f("pk_password_credentials")),
    )
    # Existing administrators cannot be assigned a password safely during an
    # unattended migration. The bootstrap command treats administrators without
    # credentials as unusable and creates a recoverable, credentialed account.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("password_credentials")
    op.drop_index(op.f("ix_api_tokens_revoked_at"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_principal_id"), table_name="api_tokens")
    op.drop_index("ix_api_tokens_principal_active", table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_expires_at"), table_name="api_tokens")
    op.drop_table("api_tokens")
    # ### end Alembic commands ###
